### ISSUE TITLE
CCR protocols don't always have our protocol ID in ccr_id field

### ISSUE THREAD

**Issue by delfuego** [presidential-innovation-fellows/clinical-trials-search#10]
We've found a few examples where our CCR protocols' ID numbers aren't in the `ccr_id` field of the API responses; I presume that this is a problem with the underlying data, but somehow we'd like to figure out how to solve this.

Examples:

* https://clinicaltrialsapi.cancer.gov/clinical-trial/NCT01434602
* https://clinicaltrialsapi.cancer.gov/clinical-trial/NCT01295944

Without a dependable field in which to find our CCR identifier, it's harder to search for our protocols via the API. It looks like all (or nearly all?) the time, our identifier will show up in `protocol_id`... but we're not sure if that's true 100% of the time. And then most-but-not-all of the time, the `ccr_id` field is also populated with it.

**Comment by michael-balint** [comment]
@delfuego: looks like we have CCR protocol ids now. Can you double-check that this is the case? Please note that the url has changed - we've added the `v1` version... https://clinicaltrialsapi.cancer.gov/v1.

**Comment by michael-balint** [comment]
Assuming this is fixed (since I can see CCR ids in trials). Please reopen if not true.
