### ISSUE TITLE
does this api only return at most ten trials

### ISSUE THREAD

**Issue by callmecary** [presidential-innovation-fellows/clinical-trials-search#15]

**Comment by michael-balint** [comment]
This project is being maintained here: https://github.com/NCIP/clinical-trials-search

Documentation for API calls is here: https://clinicaltrialsapi.cancer.gov/#!/cancer45clinical45trials/searchTrialsByGet

You can use `size` and `from` to get more data, like so: https://clinicaltrialsapi.cancer.gov/v1/clinical-trials?include=nct_id&size=100&from=10

**Comment by callmecary** [comment]
Thanks, Michael. That's helpful.
