### ISSUE TITLE
Flesh out errors when /clinical-trial/<id> endpoint returns no hit

### ISSUE THREAD

**Issue by delfuego** [presidential-innovation-fellows/clinical-trials-search#9]
Currently, if a client hits the `/clinical-trial/<id>` endpoint and no trial matching the specification is found, the only thing returned is an empty set (`{ }`). This should probably be fleshed out a bit, although given that this endpoint normally returns a simple protocol object, it's hard to know what else you'd return.

Perhaps it would make more sense to keep the response an empty set, but also set the HTTP status code to 404 to indicate that truly, no resource was found with that identifier.

**Comment by michael-balint** [comment]
Please note...

1. Changes have been committed, but not deployed to the servers just yet.
2. Kept the `todo` comment for expanding upon error messaging. We can still do a better job here, but wanted to at least address the `404`.
